# Generated by Django 4.2 on 2023-04-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('short_description', models.TextField(max_length=500)),
                ('long_description', models.TextField(max_length=2000)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
