# Generated by Django 4.2 on 2023-04-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_module', '0002_content_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='picture',
            field=models.ImageField(default=None, upload_to='upload', verbose_name=''),
        ),
    ]
