# Generated by Django 4.2 on 2023-04-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_module', '0004_alter_content_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='picture',
            field=models.ImageField(default=None, upload_to='upload', verbose_name='تصویر'),
        ),
    ]
