# Generated by Django 4.2 on 2023-04-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_module', '0005_alter_content_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
