# Generated by Django 4.2 on 2023-04-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_module', '0006_content_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.CharField(max_length=50, verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='content',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
    ]
