# Generated by Django 4.2 on 2023-04-12 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_module', '0007_content_is_active_alter_content_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان دسته بندی')),
                ('url_title', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='content',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='نمایش'),
        ),
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_module.category'),
        ),
    ]
