# Generated by Django 4.2 on 2023-04-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_module', '0009_alter_content_long_description_alter_content_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='picture',
            field=models.ImageField(default=None, upload_to='content_module/templates/content_module/upload', verbose_name='تصویر'),
        ),
    ]
