# Generated by Django 4.2 on 2023-04-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_module', '0010_alter_content_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='content',
            name='picture',
            field=models.ImageField(default=None, upload_to='static/images', verbose_name='تصویر'),
        ),
    ]
